language: python
dist: trusty
sudo: required

cache: pip

services:
 - docker

python: 3.6
env:
 - TOX_ENV=codecov
 - TOX_ENV=integration_tests-not_docker
 - TOX_ENV=integration_tests_with_jjb_trunk-not_docker
 - TOX_ENV=integration_tests-docker
   EXTRA_ARGS="-n1"
 - TOX_ENV=integration_tests_with_jjb_trunk-docker
   EXTRA_ARGS="-n1"
 - TOX_ENV=py36
 - TOX_ENV=lint
 - TOX_ENV=mypy
 - TOX_ENV=docs

matrix:
    include:
        - python: 3.5-dev
          env: TOX_ENV=py35

install:
 - pip install tox
 - docker pull jenkins/jenkins

script:
 - tox -e $TOX_ENV -- $EXTRA_ARGS
